import type { Metadata } from "next";
import { Monda } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const monda = Monda({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AppMash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monda.className}>
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
