// import type { Metadata } from "next";
// import { Monda } from "next/font/google";

// import "../app/globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

// // ✅ variable property add kiya for font CSS variable usage
// const monda = Monda({
//   weight: "400",
//   subsets: ["latin", "latin-ext"],
//   variable: "--font-monda",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "AppMash",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={monda.variable}>
//       <body className="antialiased scroll-smooth">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Monda } from "next/font/google";

import "../app/globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const monda = Monda({
  weight: ["400", "700"], // jitne weights chahiye
  subsets: ["latin", "latin-ext"],
  variable: "--font-monda",
  display: "swap",
});

export const metadata: Metadata = {
  title: "AppMash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monda.variable}>
      <head>
        {/* Font Preload */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </head>
      <body className="font-monda antialiased scroll-smooth">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
